import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
MEMORY_DIR = BASE_DIR / "memory"
LEAD_BATCH_SIZE = int(os.getenv("V2_LEAD_BATCH_SIZE", "50"))
OUTREACH_LIMIT = int(os.getenv("V2_OUTREACH_LIMIT", "40"))
FOLLOWUP_HOURS = int(os.getenv("V2_FOLLOWUP_HOURS", "24"))
LEAD_SOURCE = os.getenv("V2_LEAD_SOURCE", "real_estate")
LEAD_SOURCE_ORDER = os.getenv("V2_LEAD_SOURCE_ORDER", "real_estate,csv,api,mock")
DEFAULT_CITY = os.getenv("V2_DEFAULT_CITY", "delhi")
DEFAULT_PROPERTY_TYPE = os.getenv("V2_DEFAULT_PROPERTY_TYPE", "residential_land")
LEAD_SOURCE_CSV_PATH = os.getenv("V2_LEAD_SOURCE_CSV_PATH", "")
LEAD_SOURCE_CSV_DIR = os.getenv("V2_LEAD_SOURCE_CSV_DIR", "")
LEAD_SOURCE_API_URL = os.getenv("V2_LEAD_SOURCE_API_URL", "")
LEAD_SOURCE_API_KEY = os.getenv("V2_LEAD_SOURCE_API_KEY", "")
LEAD_SOURCE_API_URL_TEMPLATE = os.getenv("V2_LEAD_SOURCE_API_URL_TEMPLATE", "")
WHATSAPP_API_URL = os.getenv("WHATSAPP_API_URL", "")
WHATSAPP_API_TOKEN = os.getenv("WHATSAPP_API_TOKEN", "")
OLLAMA_API_URL = os.getenv("OLLAMA_API_URL", "http://127.0.0.1:11434/v1/outputs")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama2")

COMMISSION_CONVERSION_PLATFORM = float(os.getenv("COMMISSION_CONVERSION_PLATFORM", "10.0"))
COMMISSION_CONVERSION_SOURCE = float(os.getenv("COMMISSION_CONVERSION_SOURCE", "3.0"))
COMMISSION_LEAD_SALE_PLATFORM = float(os.getenv("COMMISSION_LEAD_SALE_PLATFORM", "70.0"))
COMMISSION_LEAD_SALE_SOURCE = float(os.getenv("COMMISSION_LEAD_SALE_SOURCE", "30.0"))
LATE_PAYMENT_GRACE_DAYS = int(os.getenv("LATE_PAYMENT_GRACE_DAYS", "15"))
LATE_PAYMENT_PENALTY_PERCENT_PER_WEEK = float(os.getenv("LATE_PAYMENT_PENALTY_PERCENT_PER_WEEK", "2.0"))
PAYMENT_SUSPENSION_AFTER_DAYS = int(os.getenv("PAYMENT_SUSPENSION_AFTER_DAYS", "60"))
MOBILE_CRM_API_KEY = os.getenv("MOBILE_CRM_API_KEY", "")
